MedicineSearchWebApp/MedicineSearchWebApp/Controllers/CustomerController.cs
using MedicineSearchWebApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MedicineSearchWebApp.Controllers
{
    public class CustomerController : Controller
    {
        // GET: CustomerController
        public ActionResult Index()
        {
            MedicineSearchContext context = new MedicineSearchContext();
            return View(context.Customers.ToList());
        }

        // GET: CustomerController/Details/5
        public ActionResult Details()
        {
            MedicineSearchContext cnt = new MedicineSearchContext();
            Customer ct = new Customer();
            int uid = (int)HttpContext.Session.GetInt32("userid");
            var ctdet = (from i in cnt.Customers where i.UserId == uid select i).FirstOrDefault();
            if(ctdet != null)
            {
                ct.UserId = ctdet.UserId;
                ct.UserName = ctdet.UserName;
                ct.UserMobile = ctdet.UserMobile;
                ct.UserEmail = ctdet.UserEmail;
                ct.UserArea = ctdet.UserArea;
                ct.UserCity = ctdet.UserCity;
                ct.UserWalletbal = ctdet.UserWalletbal;
                ct.AllergicTo = ctdet.AllergicTo;
            }
            return View(ct);
        }

        // GET: CustomerController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CustomerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CustomerController/Edit/5
        public ActionResult Edit(int id)
        {
            MedicineSearchContext cnt = new MedicineSearchContext();
            Customer ct = new Customer();
            var ctdet = (from i in cnt.Customers where i.UserId == id select i).FirstOrDefault();
            if (ctdet != null)
            {
                ct.UserId = ctdet.UserId;
                ct.UserName = ctdet.UserName;
                ct.UserMobile = ctdet.UserMobile;
                ct.UserEmail = ctdet.UserEmail;
                ct.UserArea = ctdet.UserArea;
                ct.UserCity = ctdet.UserCity;
                ct.UserWalletbal = ctdet.UserWalletbal;
                ct.AllergicTo = ctdet.AllergicTo;
            }
            return View(ct);
        }

        // POST: CustomerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                MedicineSearchContext cnt = new MedicineSearchContext();
                var ctdet = (from i in cnt.Customers where i.UserId == id select i).FirstOrDefault();
                if (ctdet != null)
                {
                    ctdet.UserId= int.Parse(collection["UserId"].ToString());
                    ctdet.UserName = collection["UserName"].ToString();
                    ctdet.UserMobile = collection["UserMobile"].ToString();
                    ctdet.UserEmail = collection["UserEmail"].ToString();
                    ctdet.UserArea = collection["UserArea"].ToString();
                    ctdet.UserCity = collection["UserCity"].ToString();
                    ctdet.UserWalletbal = decimal.Parse(collection["UserWalletbal"].ToString());
                    ctdet.AllergicTo = collection["AllergicTo"].ToString();
                    cnt.SaveChanges();
                }
                return RedirectToAction(nameof(Details));
            }
            catch
            {
                return View();
            }
        }

        // GET: CustomerController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CustomerController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MedicineSearchWebApp/MedicineSearchWebApp/Controllers/MemberController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MedicineSearchWebApp.Models;

namespace MedicineSearchWebApp.Controllers
{
    public class MemberController : Controller
    {
        public ActionResult AddMember()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddMember(IFormCollection collection)
        {
            try
            {
                MedicineSearchContext cnt = new MedicineSearchContext();
                Medecine md = new Medecine();
                md.ProviderId = (int)HttpContext.Session.GetInt32("vendorid");
                md.MedicineName = collection["MedicineName"].ToString();
                md.MedicineCategory = collection["MedicineCategory"].ToString();
                md.MedicineDosage = int.Parse(collection["MedicineDosage"].ToString());
                md.MedicineMdate = DateTime.Parse(collection["MedicineMdate"].ToString());
                md.MedicineEdate = DateTime.Parse(collection["MedicineEdate"].ToString());
                md.MedicineStock = int.Parse(collection["MedicineStock"].ToString());
                md.MedicinePrice = decimal.Parse(collection["MedicinePrice"].ToString());
                cnt.Medecines.Add(md);
                cnt.SaveChanges();
                return RedirectToAction(nameof(display));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult display(string sort)
        {
            MedicineSearchContext cnt = new MedicineSearchContext();
            Medecine md = new Medecine();
            ViewBag.CatSortParam = string.IsNullOrEmpty(sort) ? "CATEGORY" : "";
            ViewBag.NameSortParam = sort == "NAME" ? "DESN" : "NAME";
            ViewBag.MDATESortParam = sort == "MANUFACTURING DATE" ? "DESCM" : "MANUFACTURING DATE";
            ViewBag.EDATESortParam = sort == "EXPIRY DATE" ? "DESCE" : "EXPIRY DATE";
            ViewBag.StockSortParam = sort == "STOCK" ? "DESCS" : "STOCK";
            ViewBag.PriceSortParam = sort == "PRICE" ? "DESCP" : "PRICE";

            int vendorid = (int) HttpContext.Session.GetInt32("vendorid");
            var med = from i in cnt.Medecines where i.ProviderId == vendorid select i;
            switch (sort)
            {
                case "NAME":
                    med = med.OrderBy(i => i.MedicineName);
                    break;
                case "DESCN":
                    med = med.OrderByDescending(i => i.MedicineName);
                    break;
                case "CATEGORY":
                    med = med.OrderByDescending(i => i.MedicineCategory);
                    break;
                case "MANUFACTURING DATE":
                    med = med.OrderBy(i => i.MedicineMdate);
                    break;
                case "DESCM":
                    med = med.OrderByDescending(i => i.MedicineMdate);
                    break;
                case "EXPIRY DATE":
                    med = med.OrderBy(i => i.MedicineEdate);
                    break;
                case "DESCE":
                    med = med.OrderByDescending(i => i.MedicineEdate);
                    break;
                case "STOCK":
                    med = med.OrderBy(i => i.MedicineStock);
                    break;
                case "DESCS":
                    med = med.OrderByDescending(i => i.MedicineStock);
                    break;
                case "PRICE":
                    med = med.OrderBy(i => i.MedicinePrice);
                    break;
                case "DESCP":
                    med = med.OrderByDescending(i => i.MedicinePrice);
                    break;
                default:
                    med = med.OrderBy(i => i.MedicineCategory);
                    break;
            }
            return View(med.ToList());
        }
        public ActionResult Edit(int id)
        {
            MedicineSearchContext cnt = new MedicineSearchContext();
            Medecine md = new Medecine();
            var med = (from i in cnt.Medecines where i.MedicineId == id select i).FirstOrDefault();
            if(med != null)
            {
                md.MedicineDosage = med.MedicineDosage;
                md.MedicineMdate = med.MedicineMdate;
                md.MedicineEdate = med.MedicineEdate;
                md.MedicineStock = med.MedicineStock;
                md.MedicinePrice = med.MedicinePrice;
            }
            return View(md);
        }

        // POST: MemberController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                MedicineSearchContext cnt = new MedicineSearchContext();
                var md = (from i in cnt.Medecines where i.MedicineId == id select i).FirstOrDefault();
               if(md != null)
                {
                    md.MedicineDosage = int.Parse(collection["MedicineDosage"].ToString());
                    md.MedicineMdate = DateTime.Parse(collection["MedicineMdate"].ToString());
                    md.MedicineEdate = DateTime.Parse(collection["MedicineEdate"].ToString());
                    md.MedicineStock = int.Parse(collection["MedicineStock"].ToString());
                    md.MedicinePrice = decimal.Parse(collection["MedicinePrice"].ToString());
                }
                cnt.SaveChanges();
                return RedirectToAction(nameof(display));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            MedicineSearchContext cnt = new MedicineSearchContext();
            Medecine md = new Medecine();
            var med = (from i in cnt.Medecines where i.MedicineId == id select i).FirstOrDefault();
            if(med != null)
            {
                md.MedicineName = med.MedicineName;
                md.MedicineCategory = med.MedicineCategory;
                md.MedicineDosage = med.MedicineDosage;
                md.MedicineMdate = med.MedicineMdate;
                md.MedicineEdate = med.MedicineEdate;
                md.MedicineStock = med.MedicineStock;
                md.MedicinePrice = med.MedicinePrice;
                md.ProviderId = med.ProviderId;
            }
            return View(md);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                MedicineSearchContext cnt = new MedicineSearchContext();
                var md = (from i in cnt.Medecines where i.MedicineId == id select i).FirstOrDefault();
                cnt.Medecines.Remove(md);
                cnt.SaveChanges();
                return RedirectToAction(nameof(display));
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Details()
        {
            MedicineSearchContext cnt = new MedicineSearchContext();
            Vendor ven = new Vendor();

            int vendorid = (int)HttpContext.Session.GetInt32("vendorid");
            var vedet = from i in cnt.Vendors where i.VendorId == vendorid select i;
            if (vedet != null)
            {
                return View(vedet.ToList());
            }
            else
            {
                return View();
            }
        }
        public ActionResult EditVendor(int id)
        {
            MedicineSearchContext cnt = new MedicineSearchContext();
            Vendor ven = new Vendor();
            var vedet = (from i in cnt.Vendors where i.VendorId == id select i).FirstOrDefault();
            if (vedet != null)
            {
                ven.VendorId = vedet.VendorId;
                ven.VendorOrgName = vedet.VendorOrgName;
                ven.VendorArea = vedet.VendorArea;
                ven.VendorCity = vedet.VendorCity;
                ven.VendorMobile = vedet.VendorMobile;
                ven.VendorWallet = vedet.VendorWallet;
                ven.VendorSpeciality = vedet.VendorSpeciality;
            }
            return View(ven);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditVendor(int id, IFormCollection collection)
        {
            try
            {
                MedicineSearchContext cnt = new MedicineSearchContext();
                var vedet = (from i in cnt.Vendors where i.VendorId == id select i).FirstOrDefault();
                if (vedet != null)
                {
                    vedet.VendorId = int.Parse(collection["VendorId"].ToString());
                    vedet.VendorOrgName = collection["VendorOrgName"].ToString();
                    vedet.VendorArea = collection["VendorArea"].ToString();
                    vedet.VendorCity = collection["VendorCity"].ToString();
                    vedet.VendorMobile = collection["VendorMobile"].ToString();
                    vedet.VendorWallet = decimal.Parse(collection["VendorWallet"].ToString());
                    vedet.VendorSpeciality = collection["VendorSpeciality"].ToString();
                    cnt.SaveChanges();
                }
                return RedirectToAction(nameof(Details));
            }
            catch
            {
                return View();
            }
        }
    }
}

MedicineSearchWebApp/MedicineSearchWebApp/Views/Home/Details.cshtml
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Home/_Layout.cshtml";
}

<h1>Details</h1>

MedicineSearchWebApp/MedicineSearchWebApp/Views/Home/Index.cshtml
@model MedicineSearchWebApp.Models.Customer
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Home/_Layout.cshtml";
}


<!DOCTYPE html>


<div class="flexbox">
    <div class="leftside">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="container">
            <div class="screen">
                <div class="screen__content">
                    <form class="login" asp-action="Index">
                        <div class="login__field">
                            <i class="login__icon fas fa-user"></i>
                            <input type="text" asp-for="UserMobile" class="login__input" placeholder="User name / Mobile No." />
                           
                        </div>
                        <div class="login__field">
                            <i class="login__icon fas fa-lock"></i>
                            <input type="password" asp-for="UserPassword" class="login__input" placeholder="Password">
                        </div>
                        <button class="button login__submit" type="submit" value="Index" name="submit">
                            <span class="button__text">User LogIn</span>
                            <i class="button__icon fas fa-chevron-right"></i>
                        </button>

                        <button class="button login__submit" type="submit" value="Index1" name="submit">
                            <span class="button__text">Member LogIn</span>
                            <i class="button__icon fas fa-chevron-right"></i>
                        </button>
                    </form>
                    <div class="social-login">
                        <br />
                        <div class="social-icons">
                            <a href="#" class="social-login__icon fab fa-instagram"></a>
                            <a href="#" class="social-login__icon fab fa-facebook"></a>
                            <a href="#" class="social-login__icon fab fa-twitter"></a>
                        </div>
                    </div>
                </div>
                <div class="screen__background">
                    <span class="screen__background__shape screen__background__shape4"></span>
                    <span class="screen__background__shape screen__background__shape3"></span>
                    <span class="screen__background__shape screen__background__shape2"></span>
                    <span class="screen__background__shape screen__background__shape1"></span>
                </div>
            </div>
        </div>

    </div>
    <div class="rightside">
        <div class="mySlides fade">
            <img src="~/img1.jpg" style="width: 800px; height: 600px; object-fit: contain;">
        </div>

        <div class="mySlides fade">
            <img src="~/img2.jpg" style="width: 800px; height: 600px; object-fit: contain;">
        </div>

        <div class="mySlides fade">
            <img src="~/img3.jpg" style="width: 800px; height: 600px; object-fit: contain;">
        </div>

        <div class="mySlides fade">
            <img src="~/img4.jpg" style="width: 800px; height: 600px; object-fit: contain;">
        </div>

    </div>
    <br>

    <div style="text-align:center">
        <span class="dot"></span>
        <span class="dot"></span>
        <span class="dot"></span>
    </div>

</div>



<script src="~/js/IndexScript.js">

</script>
<script>
    var slideIndex = 0;
    showSlides();

    function showSlides() {
        var i;
        var slides = document.getElementsByClassName("mySlides");
        var dots = document.getElementsByClassName("dot");
        for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
        }
        slideIndex++;
        if (slideIndex > slides.length) { slideIndex = 1 }
        for (i = 0; i < dots.length; i++) {
            dots[i].className = dots[i].className.replace(" active", "");
        }
        slides[slideIndex - 1].style.display = "block";
        dots[slideIndex - 1].className += " active";
        setTimeout(showSlides, 2000); // Change image every 2 seconds
    }
</script>

MedicineSearchWebApp/MedicineSearchWebApp/Views/Home/UserPage.cshtml
@{
    ViewData["Title"] = "UserPage";
    Layout = "~/Views/Home/_UserLayoutAfterLogin.cshtml";
}




<br />
<br />
<br />
<br />
<div class="cards-list">

    <div class="card 1">
        <div class="card_image"> <img src="~/VendorProfile.jpg" /> </div>
        <div class="card_title title-white">
            <button style="        border: none;
        color: white;
        width: 100px;
        padding: 7px 7px 7px 7px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        background-color: #e7e7e7;
        color: black;
        border-radius: 12px;
    " onclick="location.href='@Url.Action("Details", "Customer" )'">
                View Profile
            </button>
        </div>
    </div>
    <div class="card 2">
        <div class="card_image">
            <img src="~/MedicineSearch.png" />
        </div>
        <div class="card_title title-white">
            <button style="        border: none;
        width: 130px;
        color: white;
        padding: 7px 7px 7px 7px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        background-color: #e7e7e7;
        color: black;
        border-radius: 12px;
    " onclick="location.href='@Url.Action("Index", "Medecine" )'">
                Search Medicine
            </button>
        </div>
    </div>

    <div class="card 3">
        <div class="card_image">
            <img src="~/PlaceMedicine.png" />
        </div>
        <div class="card_title">
            <button style="        border: none;
        width: 130px;
        color: white;
        padding: 7px 7px 7px 7px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        background-color: #e7e7e7;
        color: black;
        border-radius: 12px;
    " onclick="location.href='@Url.Action("Index", "Medecine" )'">
                Place Order
            </button>
        </div>
    </div>

    <div class="card 3">
        <div class="card_image">
            <img src="~/wallet.jpg" />
        </div>
        <div class="card_title">
            <button style="        border: none;
        width: 130px;
        color: white;
        padding: 7px 7px 7px 7px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        background-color: #e7e7e7;
        color: black;
        border-radius: 12px;
    " onclick="location.href='@Url.Action("Edit", "Registration" )'">
                Wallet Details
            </button>
        </div>
    </div>
</div>
<br />
<br />
<br />
<br />

MedicineSearchWebApp/MedicineSearchWebApp/Views/Home/VendorHomePage.cshtml
@{
    ViewData["Title"] = "VendorHomePage";
    Layout = "~/Views/Home/_AfterLoginVendorLayout.cshtml";
}



<br />
<br />
<br />
<br />
<div class="cards-list">

    <div class="card 1">
        <div class="card_image"> <img src="~/VendorProfile.jpg" /> </div>
        <div class="card_title title-white">
            <button style="        border: none;
        color: white;
        width: 100px;
        padding: 7px 7px 7px 7px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        background-color: #e7e7e7;
        color: black;
        border-radius: 12px;
    " onclick="location.href='@Url.Action("Details", "Member" )'">
                View Profile
            </button>
        </div>
    </div>
    <div class="card 2">
        <div class="card_image">
            <img src="~/ViewMedicine2.jpeg" />
        </div>
        <div class="card_title title-white">
            <button style="        border: none;
        width: 130px;
        color: white;
        padding: 7px 7px 7px 7px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        background-color: #e7e7e7;
        color: black;
        border-radius: 12px;
    " onclick="location.href='@Url.Action("display", "Member" )'">
                View Medicine
            </button>
        </div>
    </div>

    <div class="card 3">
        <div class="card_image">
            <img src="~/AddMedicine.png" />
        </div>
        <div class="card_title">
            <button style="        border: none;
        width: 130px;
        color: white;
        padding: 7px 7px 7px 7px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        background-color: #e7e7e7;
        color: black;
        border-radius: 12px;
    " onclick="location.href='@Url.Action("AddMember", "Member" )'">
                Add Medicine
            </button>
        </div>
    </div>

    @*<div class="card 4">
            <div class="card_image">
                <img src="https://media.giphy.com/media/LwIyvaNcnzsD6/giphy.gif" />
            </div>
            <div class="card_title title-black">
                <p>Card Title</p>
            </div>
        </div>*@

</div>
<br />
<br />
<br />
<br />

MedicineSearchWebApp/MedicineSearchWebApp/Views/Home/_AfterLoginLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link href="~/css/form.css" rel="stylesheet" />
    <link href="~/css/ProfileCard.css" rel="stylesheet" />
    <link href="~/css/StyleSheet.css" rel="stylesheet" />
    <link href="~/css/IndexStyle.css" rel="stylesheet" />

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous" />
    <link href="https://fonts.googleapis.com/css?family=Poppins:200i,300,400&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/3.6.95/css/materialdesignicons.css" />
</head>
<body>
    <section class="navigation">
        <div class="nav-container">
            <div class="brand">
                <a href="@Url.Action("UserPage", "Home" )">Medicine Search App</a>
            </div>
            <nav>
                <div class="nav-mobile"><a id="navbar-toggle" href="#!"><span></span></a></div>
                <ul class="nav-list">
                    <li>
                        <a href="@Url.Action("UserPage", "Home" )">Home</a>
                    </li>
                    <li>
                        <a href="#!">About</a>
                    </li>
                    <li>
                        <a href="#!">Services</a>
                        <ul class="navbar-dropdown">
                            <li>
                                <a href="#!">Sass</a>
                            </li>
                            <li>
                                <a href="#!">Less</a>
                            </li>
                            <li>
                                <a href="#!">Stylus</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#!">Category</a>
                        <ul class="navbar-dropdown">
                            <li>
                                <a href="#!">Sass</a>
                            </li>
                            <li>
                                <a href="#!">Less</a>
                            </li>
                            <li>
                                <a href="#!">Stylus</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#!">Contact</a>
                    </li>
                    <li>
                        <a href="#!">Log Out</a>
                    </li>
                </ul>
            </nav>
        </div>
    </section>
    <div style="min-height: 100vh;">
        @RenderBody()
    </div>
</body>
<footer id="contact">
    <ul>
        <div id="icon-container">
            <a href="#">
                <div id="icon">
                    <li><i class="fab fa-twitter"></i></li>
                </div>
            </a>
            <a href="#">
                <div id="icon">
                    <li><i class="fab fa-instagram"></i></li>
                </div>
            </a>
            <a href="#">
                <div id="icon">
                    <li><i class="fab fa-facebook-f"></i></li>
                </div>
            </a>
            <a href="#">
                <div id="icon">
                    <li><i class="far fa-envelope"></i></li>
                </div>
            </a>
            <a href="#">
                <div id="icon">
                    <li><i class="fab fa-free-code-camp"></i></li>
                </div>
            </a>
        </div>
    </ul>
    <p>&copy 2020-2021, Medicine Search</p>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
@await RenderSectionAsync("Styles", required: false)
</html>

MedicineSearchWebApp/MedicineSearchWebApp/Views/Home/_AfterLoginVendorLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/VendorHomePage.css" rel="stylesheet" type="text/css" />
    <link href="~/css/IndexStyle.css" rel="stylesheet" />

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous" />
    <link href="https://fonts.googleapis.com/css?family=Poppins:200i,300,400&display=swap" rel="stylesheet" />
</head>
<body>
    <section class="navigation">
        <div class="nav-container">
            <div class="brand">
                <a href="@Url.Action("VendorHomePage", "Home" )">Medicine Search App</a>
            </div>
            <nav>
                <div class="nav-mobile"><a id="navbar-toggle" href="#!"><span></span></a></div>
                <ul class="nav-list">
                    <li>
                        <a href="@Url.Action("VendorHomePage", "Home" )">Home</a>
                    </li>
                    <li>
                        <a href="#!">About</a>
                    </li>
                    <li>
                        <a href="#!">Contact</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Home" )">Logout</a>
                    </li>
                </ul>
            </nav>
        </div>
    </section>
    <div>
        @RenderBody()
    </div>
</body>
<footer id="contact">
    <ul>
        <div id="icon-container">
            <a href="#">
                <div id="icon">
                    <li><i class="fab fa-twitter"></i></li>
                </div>
            </a>
            <a href="#">
                <div id="icon">
                    <li><i class="fab fa-instagram"></i></li>
                </div>
            </a>
            <a href="#">
                <div id="icon">
                    <li><i class="fab fa-facebook-f"></i></li>
                </div>
            </a>
            <a href="#">
                <div id="icon">
                    <li><i class="far fa-envelope"></i></li>
                </div>
            </a>
            <a href="#">
                <div id="icon">
                    <li><i class="fab fa-free-code-camp"></i></li>
                </div>
        </div></a>
    </ul>
    <p>&copy 2020-2021, Medicine Search</p>
</footer>
</html>